# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fence < Formula
  desc "Lightweight, container-free sandbox for running commands with network and filesystem restrictions"
  homepage "https://github.com/fencesandbox/fence"
  version "0.1.66"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fencesandbox/fence/releases/download/v0.1.66/fence_0.1.66_Darwin_x86_64.tar.gz"
      sha256 "4c3099886711efcc196fed83f7a22d2917e9be9cb7b21e0949fff867363cfd69"

      define_method(:install) do
        bin.install "fence"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fencesandbox/fence/releases/download/v0.1.66/fence_0.1.66_Darwin_arm64.tar.gz"
      sha256 "cdac9e27379c601a1b4bd01000b3eacc5aea0bd8e3fa0b012356333c80aed447"

      define_method(:install) do
        bin.install "fence"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fencesandbox/fence/releases/download/v0.1.66/fence_0.1.66_Linux_x86_64.tar.gz"
      sha256 "09ac7fa27bfa80c06ce5da074abe6c7b498c42df3c95acad5e052d7dfd926830"
      define_method(:install) do
        bin.install "fence"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fencesandbox/fence/releases/download/v0.1.66/fence_0.1.66_Linux_arm64.tar.gz"
      sha256 "2eeba73c7ddf138da9e646c7a57f7e2d37c4e4443beeb7f846151c580e1374f7"
      define_method(:install) do
        bin.install "fence"
      end
    end
  end

  test do
    system "#{bin}/fence", "--version"
  end
end
